# Generated by Django 4.0.4 on 2022-05-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='klienci',
            fields=[
                ('id_klienta', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_klienta', models.CharField(max_length=255)),
                ('nip_klienta', models.CharField(max_length=10)),
                ('miejscowosc_klienta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='produkty',
            fields=[
                ('id_produktu', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_produktu', models.CharField(max_length=255)),
                ('cena_netto_za_sztuke', models.FloatField(verbose_name=2)),
            ],
        ),
    ]
